name: 117-seguridad-industrial
region: nyc

databases:
  - name: seguridad-industrial-db
    engine: PG
    version: "15"
    production: true
    cluster_name: seguridad-industrial-db

services:
  # Unified App (Frontend + Backend)
  - name: app
    github:
      repo: Servas20900/117_Seguridad_Industrial
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3001
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: "production"
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "3001"
      - key: ADMIN_USERNAME
        scope: RUN_TIME
        type: SECRET
      - key: ADMIN_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: VITE_GA_MEASUREMENT_ID
        scope: BUILD_TIME
        type: SECRET
      - key: VITE_CLOUDINARY_CLOUD_NAME
        scope: BUILD_TIME
        type: SECRET
      - key: VITE_WEB3FORMS
        scope: BUILD_TIME
        type: SECRET
    health_check:
      http_path: /api/health-check

